enum ComponentTypes
{
	NOT_FOUND = -1,
	TRANSFORM,
	MESH_RENDERER,
	BOX_COLIDER,
	SPHERE_COLIDER,
	CAMERA,
	CAMERA_FLY_CONTROLLER,
	ROTATOR,
	AUDIO_LISTENER,
	AUDIO_EVENT_EMITTER,
	TRANSFORM_FOLLOW,
	PATH_FOLLOW,
	LOOK_AT,
	PLAYER_CONTROLLER,

	EXPLOSION_CONTROLLER,
	NOISE_CONTROLLER,

	MATERIAL_SWITCHER ,
};